### PR TITLE
Introduce pre commit hook

### LINKED ISSUE #7: Initialize a pre-commit hook
Pre-commit should have:
- Ruff linter
- Ruff formatter
- mypy?

Anything else you would suggest for quality checking

### PR DESCRIPTION
**Pull request by menkotoglou**
Resolves #7.

### CODE REVIEW

**Comment by dimitrismistriotis** [comment]
Thinking of adding the installation to a makefile entry ad maybe document the practice in a Contributing.md

**Comment by menkotoglou** [comment]
Agree

**Comment by dimitrismistriotis** [comment]
Comments:

Installation should happen from the makefile

Now that we have instructions a sentence should be there that pre-commits are optional for clients/forkers of the repo

This is a `.pre-commit-config.yaml` I used in another project:

```yaml
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: "styles.css"
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
    -   id: black
-   repo: https://github.com/dosisod/refurb
    rev: "v1.16.0"
    hooks:
      - id: refurb
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.267'  # Ruff version.
    hooks:
        - id: ruff
```

As I see the project now, I get no complains for example when I do not have docstrings. I understand that `black` might not be needed. Do not know if we should beef it up a little or maybe later.

**Comment by dimitrismistriotis** [comment]
Fixing as-is for first version, will discuss mypy and others later on in separate issues.

**Pull request merged**
